// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using 국토교통부_공공데이터Common;

#nullable disable

namespace 국토교통부_공공데이터Common.Migrations
{
    [DbContext(typeof(공동주택DbContext))]
    [Migration("20240502135113_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.개별사용료", b =>
                {
                    b.Property<string>("단지코드")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("가스공용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("가스전용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("건물보험료")
                        .HasColumnType("bigint");

                    b.Property<long>("급탕공용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("급탕전용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("난방공용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("난방전용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("생활폐기물수수료")
                        .HasColumnType("bigint");

                    b.Property<long>("선거관리위원회운영비")
                        .HasColumnType("bigint");

                    b.Property<long>("수도공용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("수도전용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("입주자대표회의운영비")
                        .HasColumnType("bigint");

                    b.Property<long>("전기공용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("전기전용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("정화조오물수수료")
                        .HasColumnType("bigint");

                    b.HasKey("단지코드", "date");

                    b.ToTable("개별사용료");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.공동주택", b =>
                {
                    b.Property<string>("단지코드")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("건축물대장상연면적")
                        .HasColumnType("float");

                    b.Property<string>("관리방식")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("관리비부과면적")
                        .HasColumnType("float");

                    b.Property<string>("관리사무소연락처")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("관리사무소팩스")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("난방방식")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("단지명")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("단지분류")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("대장전용면적합계")
                        .HasColumnType("float");

                    b.Property<string>("도로명주소")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("동수")
                        .HasColumnType("int");

                    b.Property<string>("리")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("법정동주소")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("법정동코드")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("복도유형")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("분양형태")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("사용승인일")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("상세정보")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("세대수")
                        .HasColumnType("int");

                    b.Property<string>("시공사")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("시군구")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("시도")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("시행사")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("읍면동")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("전용면적별세대현황_135초과")
                        .HasColumnType("float");

                    b.Property<double>("전용면적별세대현황_60_85")
                        .HasColumnType("float");

                    b.Property<double>("전용면적별세대현황_60이하")
                        .HasColumnType("float");

                    b.Property<double>("전용면적별세대현황_85_135")
                        .HasColumnType("float");

                    b.Property<int>("호수")
                        .HasColumnType("int");

                    b.Property<string>("홈페이지주소")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("단지코드");

                    b.ToTable("공동주택");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.공용관리비", b =>
                {
                    b.Property<string>("단지코드")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("경비비")
                        .HasColumnType("bigint");

                    b.Property<long>("교육훈련비")
                        .HasColumnType("bigint");

                    b.Property<string>("기타부대비용Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("기타부대비용");

                    b.Property<long>("소독비")
                        .HasColumnType("bigint");

                    b.Property<long>("수선비")
                        .HasColumnType("bigint");

                    b.Property<long>("승강기유지비")
                        .HasColumnType("bigint");

                    b.Property<long>("시설유지비")
                        .HasColumnType("bigint");

                    b.Property<long>("안전점검비")
                        .HasColumnType("bigint");

                    b.Property<long>("위탁관리수수료")
                        .HasColumnType("bigint");

                    b.Property<string>("인건비Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("인건비");

                    b.Property<long>("재해예방비")
                        .HasColumnType("bigint");

                    b.Property<string>("제사무비Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("제사무비");

                    b.Property<string>("제세공과금Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("제세공과금");

                    b.Property<long>("지능형홈네트워크설비유지비")
                        .HasColumnType("bigint");

                    b.Property<string>("차량유지비Json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("차량유지비");

                    b.Property<long>("청소비")
                        .HasColumnType("bigint");

                    b.Property<long>("피복비")
                        .HasColumnType("bigint");

                    b.HasKey("단지코드", "date");

                    b.ToTable("공용관리비");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.에너지사용정보", b =>
                {
                    b.Property<string>("단지코드")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("가스사용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("가스사용량")
                        .HasColumnType("bigint");

                    b.Property<long>("급탕사용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("급탕사용량")
                        .HasColumnType("bigint");

                    b.Property<long>("난방사용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("난방사용량")
                        .HasColumnType("bigint");

                    b.Property<long>("수도사용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("수도사용량")
                        .HasColumnType("bigint");

                    b.Property<long>("전기사용금액")
                        .HasColumnType("bigint");

                    b.Property<long>("전기사용량")
                        .HasColumnType("bigint");

                    b.HasKey("단지코드", "date");

                    b.ToTable("에너지사용정보");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.장기수선충당금", b =>
                {
                    b.Property<string>("단지코드")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("월부과액")
                        .HasColumnType("bigint");

                    b.Property<long>("월사용액")
                        .HasColumnType("bigint");

                    b.Property<long>("적립요율")
                        .HasColumnType("bigint");

                    b.Property<long>("충당금잔액")
                        .HasColumnType("bigint");

                    b.HasKey("단지코드", "date");

                    b.ToTable("장기수선충당금");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.개별사용료", b =>
                {
                    b.HasOne("국토교통부_공공데이터Common.Model.공동주택", "공동주택")
                        .WithMany("개별사용료목록")
                        .HasForeignKey("단지코드")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("공동주택");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.공용관리비", b =>
                {
                    b.HasOne("국토교통부_공공데이터Common.Model.공동주택", "공동주택")
                        .WithMany("공용관리비목록")
                        .HasForeignKey("단지코드")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("공동주택");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.에너지사용정보", b =>
                {
                    b.HasOne("국토교통부_공공데이터Common.Model.공동주택", "공동주택")
                        .WithMany("에너지사용목록")
                        .HasForeignKey("단지코드")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("공동주택");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.장기수선충당금", b =>
                {
                    b.HasOne("국토교통부_공공데이터Common.Model.공동주택", "공동주택")
                        .WithMany("장기수선충당금목록")
                        .HasForeignKey("단지코드")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("공동주택");
                });

            modelBuilder.Entity("국토교통부_공공데이터Common.Model.공동주택", b =>
                {
                    b.Navigation("개별사용료목록");

                    b.Navigation("공용관리비목록");

                    b.Navigation("에너지사용목록");

                    b.Navigation("장기수선충당금목록");
                });
#pragma warning restore 612, 618
        }
    }
}
